repos:
  MarginCall:
    source: ../MarginCall
    url: https://github.com/shanjing/MarginCall
  google_adk-python:
    source: https://github.com/google/adk-python
    url: https://github.com/google/adk-python
